{% set name = "lazy" %}
{% set version = "1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lazy-{{ version }}.tar.gz
  sha256: 7127324ec709e8324f08cb4611c1abe01776bda53bb9ce68dc5dfa46ca0ed3e9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip

  run:
    - python >={{ python_min }}
test:
  imports:
    - lazy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
about:
  home: https://github.com/stefanholek/lazy
  summary: Lazy attributes for Python objects
  doc_url: https://pythonhosted.org/lazy/
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmlandwehr
    - thewchan
