{%set name = "lazy" %}
{%set version = "1.3" %}
{%set compress_type = "zip" %}
{%set hash_type = "sha256" %}
{%set hash_val = "c80a77bf7106ba7b27378759900cfefef38271088dc63b014bcfe610c8e68e3d" %}
{%set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: {{ build_num }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - lazy
    - lazy.tests

about:
  home: https://github.com/stefanholek/lazy
  license: BSD 2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Lazy attributes for Python objects'
  dev_url: https://github.com/stefanholek/lazy
  doc_url: https://pythonhosted.org/lazy/

extra:
  recipe-maintainers:
    - pmlandwehr
